### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by zyckk4** [LaoLittle/DrawMeme#8]
mirai版本2.12.0，Skiko版本1.1.3，DrawMeme版本1.2.4
日志如下（qq号用xxx替换）：
[0m2022-07-06 12:39:34 V/Bot.xxx: [自己专用(xxx)] zyc(xxx) -> 😬😬[0m[m
[91m2022-07-06 12:39:34 W/DrawMeme: Linked class io.ktor.client.engine.HttpClientEngineFactory in mirai-api-http-v2.2.0.mirai.jar but plugin not depend on it.[0m[m
[91m2022-07-06 12:39:34 W/DrawMeme: Class loading logic may change in feature.[0m[m
[31m2022-07-06 12:39:34 E/DrawMeme: Exception in coroutine Plugin org.laolittle.plugin.draw.DrawMeme of DrawMeme
java.lang.ExceptionInInitializerError
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.meme.EmojimixKt$supportedEmojis$2.invoke(Emojimix.kt:68)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.meme.EmojimixKt$supportedEmojis$2.invoke(Emojimix.kt:53)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.meme.EmojimixKt.getSupportedEmojis(Emojimix.kt:53)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.meme.EmojimixKt.getEmojiMix(Emojimix.kt:26)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$9.invokeSuspend(DrawMeme.kt:245)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$9.invoke(DrawMeme.kt)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$9.invoke(DrawMeme.kt)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$finding$3.invokeSuspend(MessageSubscribersBuilder.kt:377)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$finding$3.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$finding$3.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:125)
	at net.mamoe.mirai.internal.event.EventListeners.callListeners$mirai_core(EventListeners.kt:73)
	at net.mamoe.mirai.internal.event.EventListeners$callListeners$1.invokeSuspend(EventListeners.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassCastException: class io.ktor.client.engine.okhttp.OkHttp cannot be cast to class io.ktor.client.engine.HttpClientEngineFactory (io.ktor.client.engine.okhttp.OkHttp is in unnamed module of loader 'app'; io.ktor.client.engine.HttpClientEngineFactory is in unnamed module of loader 'mirai-api-http-v2.2.0.mirai.jar' @51a18b21)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.GeneralKt.<clinit>(General.kt:19)
	... 36 more
[0m[m
[0m2022-07-06 12:39:56 V/Bot.xxx: [自己专用(xxx)] zyc(xxx) -> #osu 123[0m[m
[31m2022-07-06 12:39:56 E/DrawMeme: Exception in coroutine Plugin org.laolittle.plugin.draw.DrawMeme of DrawMeme
java.lang.NoClassDefFoundError: Could not initialize class org.laolittle.plugin.draw.GeneralKt
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.meme.OsuKt.<clinit>(Osu.kt:12)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$10.invokeSuspend(DrawMeme.kt:251)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$10.invoke(DrawMeme.kt)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$10.invoke(DrawMeme.kt)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$finding$3.invokeSuspend(MessageSubscribersBuilder.kt:377)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$finding$3.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.event.MessageSubscribersBuilder$finding$3.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:125)
	at net.mamoe.mirai.internal.event.EventListeners.callListeners$mirai_core(EventListeners.kt:73)
	at net.mamoe.mirai.internal.event.EventListeners$callListeners$1.invokeSuspend(EventListeners.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m[m
[0m2022-07-06 12:40:43 V/Bot.xxx: [自己专用(xxx)] zyc(xxx) -> #ph 123[0m[m
[31m2022-07-06 12:40:43 E/DrawMeme: Exception in coroutine Plugin org.laolittle.plugin.draw.DrawMeme of DrawMeme
java.lang.NoClassDefFoundError: Could not initialize class org.laolittle.plugin.draw.GeneralKt
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$1.invokeSuspend(DrawMeme.kt:54)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$1.invoke(DrawMeme.kt)
	at DrawMeme-1.2.4.mirai.jar//org.laolittle.plugin.draw.DrawMeme$onEnable$2$1.invoke(DrawMeme.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invokeSuspend(messageSubscribersInternal.kt:58)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:253)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
	at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:125)
	at net.mamoe.mirai.internal.event.EventListeners.callListeners$mirai_core(EventListeners.kt:73)
	at net.mamoe.mirai.internal.event.EventListeners$callListeners$1.invokeSuspend(EventListeners.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m[m
[92m2022-07-06 12:40:50 I/Bot.xxx: Bot cancelled: Job was cancelled[0m[m

**Comment by zyckk4** [comment]
> 还是和SkikoMirai之前的错误一致，和mah插件依赖冲突（console 2.12 修改加载器导致的）

非常感谢！把mirai-api-http更新到v2.5.0之后就正常了

**Comment by LaoLittle** [comment]
啊这
